export const EquiposMonks = [
  {
    "id": 15251,
    "legacy_id": 1355,
    "name": "Uruguay",
    "short_code": "URY",
    "twitter": null,
    "country_id": 158,
    "national_team": true,
    "founded": 1900,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/19/15251.png",
    "venue_id": 10900
  },
  {
    "id": 18546,
    "legacy_id": 2027,
    "name": "Egypt",
    "short_code": "EGY",
    "twitter": null,
    "country_id": 886,
    "national_team": true,
    "founded": 1921,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/18/18546.png",
    "venue_id": 58
  },
  {
    "id": 18551,
    "legacy_id": 1354,
    "name": "Morocco",
    "short_code": "MAR",
    "twitter": null,
    "country_id": 1424,
    "national_team": true,
    "founded": 1955,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/23/18551.png",
    "venue_id": 1679
  },
  {
    "id": 18554,
    "legacy_id": 1348,
    "name": "Tunisia",
    "short_code": "TUN",
    "twitter": null,
    "country_id": 1439,
    "national_team": true,
    "founded": 1957,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/26/18554.png",
    "venue_id": 2562
  },
  {
    "id": 18558,
    "legacy_id": 1846,
    "name": "Senegal",
    "short_code": "SEN",
    "twitter": null,
    "country_id": 200,
    "national_team": true,
    "founded": 1960,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/30/18558.png",
    "venue_id": 14382
  },
  {
    "id": 18562,
    "legacy_id": 2048,
    "name": "Saudi Arabia",
    "short_code": "SAU",
    "twitter": null,
    "country_id": 35376,
    "national_team": true,
    "founded": 1956,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/2/18562.png",
    "venue_id": 1503
  },
  {
    "id": 18564,
    "legacy_id": 211,
    "name": "Sweden",
    "short_code": "SWE",
    "twitter": null,
    "country_id": 47,
    "national_team": true,
    "founded": 1904,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/4/18564.png",
    "venue_id": 1668
  },
  {
    "id": 18567,
    "legacy_id": 1837,
    "name": "Korea Republic",
    "short_code": "KOR",
    "twitter": null,
    "country_id": 712,
    "national_team": true,
    "founded": 1933,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/7/18567.png",
    "venue_id": 175
  },
  {
    "id": 18576,
    "legacy_id": 1356,
    "name": "Mexico",
    "short_code": "MEX",
    "twitter": null,
    "country_id": 458,
    "national_team": true,
    "founded": 1927,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/16/18576.png",
    "venue_id": 1599
  },
  {
    "id": 18583,
    "legacy_id": 202,
    "name": "Denmark",
    "short_code": "DNK",
    "twitter": null,
    "country_id": 320,
    "national_team": true,
    "founded": 1889,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/23/18583.png",
    "venue_id": 5660
  },
  {
    "id": 18588,
    "legacy_id": 206,
    "name": "Croatia",
    "short_code": "CRO",
    "twitter": null,
    "country_id": 266,
    "national_team": true,
    "founded": 1912,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/28/18588.png",
    "venue_id": 176
  },
  {
    "id": 18597,
    "legacy_id": 1347,
    "name": "Japan",
    "short_code": "JPN",
    "twitter": null,
    "country_id": 479,
    "national_team": true,
    "founded": 1921,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/5/18597.png",
    "venue_id": 14408
  },
  {
    "id": 18598,
    "legacy_id": 1211,
    "name": "Costa Rica",
    "short_code": "CRI",
    "twitter": null,
    "country_id": 1739,
    "national_team": true,
    "founded": 1921,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/6/18598.png",
    "venue_id": 10981
  },
  {
    "id": 18635,
    "legacy_id": 212,
    "name": "Iceland",
    "short_code": "ICE",
    "twitter": null,
    "country_id": 1796,
    "national_team": true,
    "founded": 1947,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/11/18635.png",
    "venue_id": 7000
  },
  {
    "id": 18644,
    "legacy_id": 1350,
    "name": "Argentina",
    "short_code": "ARG",
    "twitter": null,
    "country_id": 44,
    "national_team": true,
    "founded": 1893,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/20/18644.png",
    "venue_id": 6569
  },
  {
    "id": 18645,
    "legacy_id": 208,
    "name": "England",
    "short_code": "ENG",
    "twitter": null,
    "country_id": 462,
    "national_team": true,
    "founded": 1863,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/21/18645.png",
    "venue_id": 1315
  },
  {
    "id": 18647,
    "legacy_id": 209,
    "name": "France",
    "short_code": "FRA",
    "twitter": null,
    "country_id": 17,
    "national_team": true,
    "founded": 1919,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/23/18647.png",
    "venue_id": 14433
  },
  {
    "id": 18652,
    "legacy_id": 1342,
    "name": "Iran",
    "short_code": "IRN",
    "twitter": null,
    "country_id": 488,
    "national_team": true,
    "founded": 1920,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/28/18652.png",
    "venue_id": 1984
  },
  {
    "id": 18660,
    "legacy_id": 200,
    "name": "Germany",
    "short_code": "GER",
    "twitter": null,
    "country_id": 11,
    "national_team": true,
    "founded": 1900,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/4/18660.png",
    "venue_id": 1944
  },
  {
    "id": 18699,
    "legacy_id": 199,
    "name": "Poland",
    "short_code": "POL",
    "twitter": null,
    "country_id": 2,
    "national_team": true,
    "founded": 1919,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/11/18699.png",
    "venue_id": 14452
  },
  {
    "id": 18701,
    "legacy_id": 201,
    "name": "Portugal",
    "short_code": "POR",
    "twitter": null,
    "country_id": 20,
    "national_team": true,
    "founded": 1914,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/13/18701.png",
    "venue_id": 14455
  },
  {
    "id": 18702,
    "legacy_id": 198,
    "name": "Russia",
    "short_code": "RUS",
    "twitter": null,
    "country_id": 227,
    "national_team": true,
    "founded": 1912,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/14/18702.png",
    "venue_id": 177923
  },
  {
    "id": 18704,
    "legacy_id": 1341,
    "name": "Brazil",
    "short_code": "BRA",
    "twitter": null,
    "country_id": 5,
    "national_team": true,
    "founded": 1914,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/16/18704.png",
    "venue_id": 392
  },
  {
    "id": 18708,
    "legacy_id": 230,
    "name": "Switzerland",
    "short_code": "SWI",
    "twitter": null,
    "country_id": 62,
    "national_team": true,
    "founded": 1895,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/20/18708.png",
    "venue_id": 9576
  },
  {
    "id": 18710,
    "legacy_id": 204,
    "name": "Spain",
    "short_code": "ESP",
    "twitter": null,
    "country_id": 32,
    "national_team": true,
    "founded": 1913,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/22/18710.png",
    "venue_id": 2020
  },
  {
    "id": 18717,
    "legacy_id": 1367,
    "name": "Panama",
    "short_code": "PAN",
    "twitter": null,
    "country_id": 65437,
    "national_team": true,
    "founded": 1937,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/29/18717.png",
    "venue_id": 6860
  },
  {
    "id": 18720,
    "legacy_id": 1820,
    "name": "Colombia",
    "short_code": "COL",
    "twitter": null,
    "country_id": 353,
    "national_team": true,
    "founded": 1924,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/0/18720.png",
    "venue_id": 5048
  },
  {
    "id": 18730,
    "legacy_id": 1332,
    "name": "Australia",
    "short_code": "AUS",
    "twitter": null,
    "country_id": 98,
    "national_team": true,
    "founded": 1961,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/10/18730.png",
    "venue_id": 14477
  },
  {
    "id": 18737,
    "legacy_id": 1335,
    "name": "Nigeria",
    "short_code": "NGA",
    "twitter": null,
    "country_id": 716,
    "national_team": true,
    "founded": 1945,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/17/18737.png",
    "venue_id": 12733
  },
  {
    "id": 18743,
    "legacy_id": 219,
    "name": "Belgium",
    "short_code": "BEL",
    "twitter": null,
    "country_id": 556,
    "national_team": true,
    "founded": 1895,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/23/18743.png",
    "venue_id": 2318
  },
  {
    "id": 18775,
    "legacy_id": 1364,
    "name": "Peru",
    "short_code": "PER",
    "twitter": null,
    "country_id": 338,
    "national_team": true,
    "founded": 1922,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/23/18775.png",
    "venue_id": 11432
  },
  {
    "id": 18873,
    "legacy_id": 248,
    "name": "Serbia",
    "short_code": "SRB",
    "twitter": null,
    "country_id": 296,
    "national_team": true,
    "founded": 1919,
    "logo_path": "https://cdn.sportmonks.com/images/soccer/teams/25/18873.png",
    "venue_id": 1590
  }
];
