export const RondaEliminacion = {
      "name": "Ronda de 16",
      "matches": [
      {
        "name": 49,
        "type": "qualified",
        "home_team": "winner_a",
        "away_team": "runner_b",
        "home_result": null,
        "away_result": null,
        "home_penalty": null,
        "away_penalty": null,
        "winner": null,
        "date": "2018-06-30T17:00:00+03:00",
        "stadium": 11,
        "channels": [4],
        "finished": false,
        "matchday": 4
      },
      {
        "name": 50,
        "type": "qualified",
        "home_team": "winner_c",
        "away_team": "runner_d",
        "home_result": null,
        "away_result": null,
        "home_penalty": null,
        "away_penalty": null,
        "winner": null,
        "date": "2018-06-30T21:00:00+03:00",
        "stadium": 5,
        "channels": [4,6],
        "finished": false,
        "matchday": 4
      },
      {
        "name": 51,
        "type": "qualified",
        "home_team": "winner_b",
        "away_team": "runner_a",
        "home_result": null,
        "away_result": null,
        "home_penalty": null,
        "away_penalty": null,
        "winner": null,
        "date": "2018-07-01T17:00:00+03:00",
        "stadium": 1,
        "channels": [3],
        "finished": false,
        "matchday": 4
      },
      {
        "name": 52,
        "type": "qualified",
        "home_team": "winner_d",
        "away_team": "runner_c",
        "home_result": null,
        "away_result": null,
        "home_penalty": null,
        "away_penalty": null,
        "winner": null,
        "date": "2018-07-01T21:00:00+03:00",
        "stadium": 6,
        "channels": [4,6],
        "finished": false,
        "matchday": 4
      },
      {
        "name": 53,
        "type": "qualified",
        "home_team": "winner_e",
        "away_team": "runner_f",
        "home_result": null,
        "away_result": null,
        "home_penalty": null,
        "away_penalty": null,
        "winner": null,
        "date": "2018-07-02T18:00:00+04:00",
        "stadium": 7,
        "channels": [3,6],
        "finished": false,
        "matchday": 4
      },
      {
        "name": 54,
        "type": "qualified",
        "home_team": "winner_g",
        "away_team": "runner_h",
        "home_result": null,
        "away_result": null,
        "home_penalty": null,
        "away_penalty": null,
        "winner": null,
        "date": "2018-07-02T21:00:00+03:00",
        "stadium": 10,
        "channels": [3,6],
        "finished": false,
        "matchday": 4
      },
      {
        "name": 55,
        "type": "qualified",
        "home_team": "winner_f",
        "away_team": "runner_e",
        "home_result": null,
        "away_result": null,
        "home_penalty": null,
        "away_penalty": null,
        "winner": null,
        "date": "2018-07-03T17:00:00+03:00",
        "stadium": 3,
        "channels": [4,6],
        "finished": false,
        "matchday": 4
      },
      {
        "name": 56,
        "type": "qualified",
        "home_team": "winner_h",
        "away_team": "runner_g",
        "home_result": null,
        "away_result": null,
        "home_penalty": null,
        "away_penalty": null,
        "winner": null,
        "date": "2018-07-03T21:00:00+03:00",
        "stadium": 2,
        "channels": [3,6],
        "finished": false,
        "matchday": 4
      }
    ]
  };

